### ISSUE TITLE
example-content should not be packaged

### ISSUE THREAD

**Issue by KittyGiraudel** [edenspiekermann/faster-react-tabs#10]

**Comment by KittyGiraudel** [comment]
Ping @eschaefer for opinion.

**Comment by eschaefer** [comment]
This was a discussion we had at dev couch a long time ago, more generally about how do we package react components to be cleanly installable from `npm` but also have a working example available? A lot of components listed on http://react-components.com for example unfortunately do have styles packaged with them. A git branch could be an option here... like have the example-content in an `example` branch, and make a note of this in the `description` field of `package.json`.

**Comment by oyeanuj** [comment]
Another option could be to have the source code available from the github-pages, in that branch. That way, someone could see the example with the source code in tandem and use the github-pages branch.
