### ISSUE TITLE
Missing dependency: "classnames"

### ISSUE THREAD

**Issue by adamrenklint** [edenspiekermann/faster-react-tabs#4]
The module `classnames` is listed as a devDependency, but is required in https://github.com/edenspiekermann/faster-react-tabs/blob/master/components/tabs/index.jsx, making this module break for projects that does not already have `classnames` in the dependency graph.

**Comment by eschaefer** [comment]
Thanks! Should be fixed in https://github.com/edenspiekermann/faster-react-tabs/commit/8cb309c8d2869a1e4e03f84e0cca5c21d7acb8d8
