### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by oyeanuj** [edenspiekermann/faster-react-tabs#5]
Hi @eschaefer! Thanks for this component! Are there any plans to add a11y features to the tabs so that they work with just the keyboard itself?

**Comment by eschaefer** [comment]
@oyeanuj You're welcome! That's actually an excellent idea, and I'll work on this in the next couple of days. cc @HugoGiraudel since this is right in your wheelhouse too.

**Comment by KittyGiraudel** [comment]
Yo. I'll check this when I get time.

**Comment by oyeanuj** [comment]
Thank you!
